### ISSUE TITLE
Get rid of time.Sleep in tests

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/optimint#96]
There are some tests (especially related to P2P communication) where occasionally there are some timeouts on GitHub actions. Those tests are constructed in following manner:
* setup
* sleep and assume that setup is complete
* execute code
* sleep and assume that test is complete
* check the test assertions

Increasing sleep time is a bad idea, because it makes tests run longer then needed and still there are some timeouts in CI.
Ideally, tests assertions should be somehow triggered when execution is completed (maybe mock functions should send something to a channel, or use a WaitGroup).
Other approach is to check assertions at some short interval.

Both proposed solutions require timeout mechanism, to prevent endless wait.

**Comment by ntsanov** [comment]
I'm just writing a short update since it's been a while. I've had some time to take a look at some other tests today
### [`rpcclient>local_test`](https://github.com/celestiaorg/optimint/blob/main/rpcclient/local_test.go)
[`Sleep #1`](https://github.com/celestiaorg/optimint/blob/main/rpcclient/local_test.go#L264)  - This one can be removed by using Mempool.TxsAvailable()
[`Sleep #2`](https://github.com/celestiaorg/optimint/blob/main/rpcclient/local_test.go#L242) - This one is needed because it seems Gossiping TX happens before peers are connected. It seems there is no callback, channel or some kind of notification bus that could be used to get notified on [`connect`](https://github.com/celestiaorg/optimint/blob/main/p2p/client.go#L267), or at least I could not find one.  Unless some changes are made to the client or I am wrong I guess this one would have to stay

P.S I am dragging it a bit because of lack of time but also taking the time to get familiar with the codebase, hope it is alright.
